In [1]:
"hi"

'hi'

In [5]:
print("Welcome to all")

Welcome to all


# Numpy
- Numerical Python
- open source library
- Easy to use
- handles only numerical type data
- can create multidimentional arrays
- can create arrays using
    - list
    - tuple
- 622 methods 
- it's used for mathametical operations
- Easy and much faster compared to other

In [7]:
import numpy as np

In [10]:
len(dir(np))

622

In [11]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [12]:
# creating 1D array
li = [12,3,4,5,56]
n1 = np.array(li)
n1

array([12,  3,  4,  5, 56])

In [13]:
n1.ndim

1

In [14]:
len(n1)

5

In [15]:
n1.shape

(5,)

In [16]:
n1.dtype

dtype('int32')

In [17]:
# 2D array - collection of 1D array
n2 = np.array([[1,2,3], [4,5,6],[7,8,9]])
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n2.shape

(3, 3)

In [20]:
n2*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
n2+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [22]:
n2+n2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
n3 = np.arange(1,100,10)
# factors of 10, 1,2,5,10
n3.reshape((5,2))

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

In [28]:
n4 = np.linspace(1,10,10)
n4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
n5 = np.random.random()
n5
# it returns any random value from 0 to 1

0.5471275632266862

In [35]:
np.random.randint(1,100)
# it returns integer value from given boundaries

37

In [36]:
np.random.randint(1,100, 5)

array([41, 72, 88, 57, 54])

In [43]:
# generate 6 didgit OTP
np.random.randint(100000,999999)

681586

In [45]:
np.eye(5,dtype = "int" )

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
np.ones((5,5), dtype = "str")

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [49]:
np.zeros((4,3), dtype = "int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.full((5,3), "sdc")

array([['sdc', 'sdc', 'sdc'],
       ['sdc', 'sdc', 'sdc'],
       ['sdc', 'sdc', 'sdc'],
       ['sdc', 'sdc', 'sdc'],
       ['sdc', 'sdc', 'sdc']], dtype='<U3')

In [58]:
n5 = np.arange(10,50,2)
n5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [60]:
np.power(n5,2)

array([ 100,  144,  196,  256,  324,  400,  484,  576,  676,  784,  900,
       1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304], dtype=int32)

In [62]:
np.sqrt(n5)

array([3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ,
       6.32455532, 6.4807407 , 6.63324958, 6.78232998, 6.92820323])

In [64]:
np.log(n5)

array([2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227, 3.09104245, 3.17805383, 3.25809654, 3.33220451,
       3.40119738, 3.4657359 , 3.52636052, 3.58351894, 3.63758616,
       3.68887945, 3.73766962, 3.78418963, 3.8286414 , 3.87120101])

In [65]:
min(n5)

10

In [66]:
max(n5)

48

In [68]:
np.mean(n5)

29.0

In [69]:
np.median(n5)

29.0

In [70]:
np.sin(n5)

array([-0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162,  0.55142668,  0.52908269, -0.99177885,  0.29636858,
        0.74511316, -0.91652155,  0.01770193,  0.90178835, -0.76825466])

In [72]:
n6 = np.arange(1,100,2)
n6.shape
# 50 - factors

(50,)

In [90]:
n6 = n6.reshape(5,2,5,1)
n6

array([[[[ 1],
         [ 3],
         [ 5],
         [ 7],
         [ 9]],

        [[11],
         [13],
         [15],
         [17],
         [19]]],


       [[[21],
         [23],
         [25],
         [27],
         [29]],

        [[31],
         [33],
         [35],
         [37],
         [39]]],


       [[[41],
         [43],
         [45],
         [47],
         [49]],

        [[51],
         [53],
         [55],
         [57],
         [59]]],


       [[[61],
         [63],
         [65],
         [67],
         [69]],

        [[71],
         [73],
         [75],
         [77],
         [79]]],


       [[[81],
         [83],
         [85],
         [87],
         [89]],

        [[91],
         [93],
         [95],
         [97],
         [99]]]])

In [78]:
n6[0].min()

1

In [80]:
n6.min(axis = 1)

array([ 1, 21, 41, 61, 81])

In [82]:
n6.max(axis = 0)

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [84]:
n6.mean(axis = 1)

array([10., 30., 50., 70., 90.])

In [85]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [86]:
help(np.ceil)

Help on ufunc object:

ceil = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 

# Pandas

In [91]:
import pandas as pd

In [92]:
s1 = pd.Series((23,345,56,23,23,45))
s1

0     23
1    345
2     56
3     23
4     23
5     45
dtype: int64

In [96]:
s2 = pd.Series([12,234.5,56.34])
s2.index = ["X", "Y", "Z"]

In [97]:
s2

X     12.00
Y    234.50
Z     56.34
dtype: float64

In [102]:
di = {
    "Name" : ["sai", "Srinu", "pavani", "aswini"],
    "Gender" : ["M", "M", "F", "F"], 
    "Pin" : [123,654,534,222]
}
df = pd.DataFrame(di)
df.index = list("STOP")
df

Name Gender  Pin
S     sai      M  123
T   Srinu      M  654
O  pavani      F  534
P  aswini      F  222

In [100]:
df.columns

Index(['Name', 'Gender', 'Pin'], dtype='object')

In [104]:
data = pd.read_csv("https://raw.githubusercontent.com/LavanyaPolamarasetty/Datasets/master/Classification/titanic.csv")
data.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [105]:
data.shape

(891, 11)

In [107]:
data.isnull().sum()

survived      0
pclass        0
name          0
sex           0
age         177
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

In [109]:
data["name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: name, Length: 891, dtype: object

In [110]:
type(data["name"])

pandas.core.series.Series

In [113]:
data[["name", "survived"]] # sub dataframe

name  survived
0                              Braund, Mr. Owen Harris         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                               Heikkinen, Miss. Laina         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4                             Allen, Mr. William Henry         0
..                                                 ...       ...
886                              Montvila, Rev. Juozas         0
887                       Graham, Miss. Margaret Edith         1
888           Johnston, Miss. Catherine Helen "Carrie"         0
889                              Behr, Mr. Karl Howell         1
890                                Dooley, Mr. Patrick         0

[891 rows x 2 columns]

In [115]:
data[100:101]

survived  pclass                     name     sex   age  sibsp  parch  \
100         0       3  Petranec, Miss. Matilda  female  28.0      0      0   

     ticket    fare cabin embarked  
100  349245  7.8958   NaN        S

In [120]:
data.loc[[100,120, 233], ["name", "sex"]]

name     sex
100         Petranec, Miss. Matilda  female
120     Hickman, Mr. Stanley George    male
233  Asplund, Miss. Lillian Gertrud  female

In [121]:
data.iloc[800]

survived                       0
pclass                         2
name        Ponesell, Mr. Martin
sex                         male
age                           34
sibsp                          0
parch                          0
ticket                    250647
fare                          13
cabin                        NaN
embarked                       S
Name: 800, dtype: object

In [124]:
data[data["sex"] == "female"] # data masking

survived  pclass                                               name  \
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
8           1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9           1       2                Nasser, Mrs. Nicholas (Adele Achem)   
..        ...     ...                                                ...   
880         1       2       Shelley, Mrs. William (Imanita Parrish Hall)   
882         0       3                       Dahlberg, Miss. Gerda Ulrika   
885         0       3               Rice, Mrs. William (Margaret Norton)   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   

        sex   age  sibsp  parch            ticket     fare cabin embarked  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
8    female  27.0      0      2            347742  11.1333   NaN        S  
9    female  14.0      1      0            237736  30.0708   NaN        C  
..      ...   ...    ...    ...               ...      ...   ...      ...  
880  female  25.0      0      1            230433  26.0000   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 11 columns]

In [125]:
data.sort_values('name')

survived  pclass                                   name     sex   age  \
845         0       3                    Abbing, Mr. Anthony    male  42.0   
746         0       3            Abbott, Mr. Rossmore Edward    male  16.0   
279         1       3       Abbott, Mrs. Stanton (Rosa Hunt)  female  35.0   
308         0       2                    Abelson, Mr. Samuel    male  30.0   
874         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   
..        ...     ...                                    ...     ...   ...   
286         1       3                de Mulder, Mr. Theodore    male  30.0   
282         0       3              de Pelsmaeker, Mr. Alfons    male  16.0   
361         0       2              del Carlo, Mr. Sebastiano    male  29.0   
153         0       3        van Billiard, Mr. Austin Blyler    male  40.5   
868         0       3            van Melkebeke, Mr. Philemon    male   NaN   

     sibsp  parch         ticket     fare cabin embarked  
845      0      0      C.A. 5547   7.5500   NaN        S  
746      1      1      C.A. 2673  20.2500   NaN        S  
279      1      1      C.A. 2673  20.2500   NaN        S  
308      1      0      P/PP 3381  24.0000   NaN        C  
874      1      0      P/PP 3381  24.0000   NaN        C  
..     ...    ...            ...      ...   ...      ...  
286      0      0         345774   9.5000   NaN        S  
282      0      0         345778   9.5000   NaN        S  
361      1      0  SC/PARIS 2167  27.7208   NaN        C  
153      0      2       A/5. 851  14.5000   NaN        S  
868      0      0         345777   9.5000   NaN        S  

[891 rows x 11 columns]

In [127]:
data["age"].fillna(25, inplace = True)

In [129]:
data.isnull().sum()

survived      0
pclass        0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

In [131]:
data["survived"].mode()

0    0
dtype: int64

In [134]:
data["survived"].value_counts()

0    549
1    342
Name: survived, dtype: int64

In [135]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   name      891 non-null    object 
 3   sex       891 non-null    object 
 4   age       891 non-null    float64
 5   sibsp     891 non-null    int64  
 6   parch     891 non-null    int64  
 7   ticket    891 non-null    object 
 8   fare      891 non-null    float64
 9   cabin     204 non-null    object 
 10  embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


In [136]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   28.765623    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.136649    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   25.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [139]:
data.isnull().sum()
# to identyify any null char(nan) in our data, it returns bool array

survived      0
pclass        0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

In [141]:
data.notnull().sum()

survived    891
pclass      891
name        891
sex         891
age         891
sibsp       891
parch       891
ticket      891
fare        891
cabin       204
embarked    889
dtype: int64